version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: crm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  app:
    depends_on: 
      - db
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - 3000:3000
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: crm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
