version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: crm
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network
      - db_network

networks:
  app_network:
  db_network:
