version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - 3310:3306
    volumes:
      - ./.data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: crm
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  app:
    depends_on: 
      - db
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - 3000:3000
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: crm
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
